### ISSUE TITLE
CTC Migration - POOL multiple records with READ_ONLY = 'N'

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#67] opened 2024-04-26 10:37 UTC
### What would you like to change?
Sanitise data so only one record (per juror number and pool number) has a READ_ONLY status of 'N'

### How do you think that would improve the project?
Allow the data migration scripts to identify which records should be migrated

### If this entry is related to a bug, please provide the steps to reproduce it
```
select
	count(1),
	part_no,
	pool_no,
	read_only
from
	juror.pool
group by
	part_no,
	pool_no,
	read_only
having
	count(1) > 1
```

![image](https://github.com/hmcts/juror-database-migration/assets/62246193/7cfa2c8a-6ab4-4f69-80f2-47901a440869)

**Comment by ChrisWCGI** [comment] 2024-05-29 15:11
The bureau and court copy of a juror record can both have read_only = 'N' if the court moved the juror into a pool that the bureau previously moved the juror out of.

e.g.
bureau summons for pool x
bureau moves juror to pool y
court copy of record created in pool y by pool transfer job
court moves juror to pool x

the bureau copy of the record in pool x has is_active = 'N' but still has read_only = 'N'.

**Comment by ChrisWCGI** [comment] 2024-05-30 15:00
Duplicate of issue #96

**Closed by ChrisWCGI** 2024-05-30 15:00 UTC
